### ISSUE TITLE
mount error with docker on windows

### ISSUE THREAD

**Issue by jwende** [SAP/i40-aas#41]
Hi,

I'm using docker / docker-compose on W10. If I run _docker-compose up_  it fails with:

ERROR: for i40-aas_rabbitmq_1  Cannot start service rabbitmq: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/host_mnt/c/2_Git/i40-aas/k8s/rabbitmq-broker/enabled_plugins\\\" to rootfs \\\"/var/lib/docker/overlay2/10dd0ad9b75796ba4fe5013b922c1309b9788ea863c4719741f81b728c27f2a9/merged\\\" at \\\"/var/lib/docker/overlay2/10dd0ad9b75796ba4fe5013b922c1309b9788ea863c4719741f81b728c27f2a9/merged/etc/rabbitmq/enabled_plugins\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

_ERROR: for rabbitmq  Cannot start service rabbitmq: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/host_mnt/c/2_Git/i40-aas/k8s/rabbitmq-broker/enabled_plugins\\\" to rootfs \\\"/var/lib/docker/overlay2/10dd0ad9b75796ba4fe5013b922c1309b9788ea863c4719741f81b728c27f2a9/merged\\\" at \\\"/var/lib/docker/overlay2/10dd0ad9b75796ba4fe5013b922c1309b9788ea863c4719741f81b728c27f2a9/merged/etc/rabbitmq/enabled_plugins\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project._

It starts if I remove the volume definition for rabbit-mq.

Cheers
J.

**Comment by heldic** [comment]
Hi,

thanks for opening the issue! This should be fixed with the PR just reviewed & pushed to master (https://github.com/SAP/i40-aas/pull/40). The volume definition was not up to date after the recent restructuring. It should work fine now. 

Cheers!

**Comment by jwende** [comment]
Thanks a lot - refreshed the project and it starts now without any changes !
J.
