### ISSUE TITLE
endpoint-registry does not return "protocol" attribute

### ISSUE THREAD

**Issue by oliver-goetz** [SAP/i40-aas#45]
When calling **/endpoints** endpoint of [endpoint-registry](https://github.com/SAP/i40-aas/tree/master/apps/endpoint-registry) app, it does not return **protocol** attribute.

**Comment by oliver-goetz** [comment]
If endpoint **protocol** is **http** or **https** the attribute is returned. 
For any other value it is working, but registering those endpoints succeeds with status 200.

**Comment by akiskips** [comment]
Its because of an enum used for Protocols in IRegistryResultSet.ts
@Manu3756 Should we remove this restriction or leave it but throw an error when registering a protocol not included in enum ?

`enum Protocols {
  https = 'https',
  http = 'http',
  ws = 'ws',
  wss = 'wss'
}`

**Comment by Manu3756** [comment]
We should remove the restriction and should harmonize the names all toLowerCase() eg.

**Comment by akiskips** [comment]
Ok, ill add the change to the ongoing PR of the registry

**Comment by akiskips** [comment]
Changes pushed, enum restriction removed
